language: python
env:
  - TOXENV=py27-1.7.x
  - TOXENV=py27-1.8.x
  - TOXENV=py33-1.7.x
  - TOXENV=py33-1.8.x
  - TOXENV=py34-1.7.x
  - TOXENV=py34-1.8.x
install:
  - pip install tox
  - pip install coveralls
script:
  - coverage run --source=taggit_forms tox -e $TOXENV
after_success:
  coveralls
